version: '3' 

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint:  dockerize --wait tcp://db:3306 -timeout 20s /usr/src/app/docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on:
      - db
      - nginx

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABSE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  nginx:
    build:
      context: ./nginx
    restart: always
    ports: 
      - "8080:8080"
networks:
  node-network:
    driver: bridge